# -*- coding: utf-8 -*-
"""salary_predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ML0I7fVUkhLa-7RwBzCwaI0m4WCuY8gZ
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer


data = pd.read_csv('/content/Salary Data.csv')
data

x = data['Years of Experience'].values.reshape(-1, 1)
y = data['Salary'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

model= LinearRegression()

print(data.isnull().sum())

imputer = SimpleImputer(strategy='mean')

x = imputer.fit_transform(x)
y = imputer.fit_transform(y)


model = LinearRegression()

model.fit(x, y)

next_salary = model.predict([[4.0]])
print(int(next_salary))

model.score(x, y)